### ISSUE TITLE
Set up automatic code validation

### ISSUE THREAD

**Issue by telezhnaya** [near/near-analytics#32]
@chefsale @mhalambek 

I want to run
```
black .
```
and check if the sources changed. If something is changed, we shouldn't be able to merge the PR.

**Comment by mhalambek** [comment]
So it's a format checker like yapf. We can add that, not sure how quickly you need it done.

**Comment by frol** [comment]
On CI you just need to run `black --check .` and fail CI if the returned status code is non-zero

**Comment by frol** [comment]
I have added the CI setup based on Github Actions in #33.
