### ISSUE TITLE
Rewrite `deployed_contracts` implementation

### ISSUE THREAD

**Issue by telezhnaya** [near/near-analytics#8]
https://near.zulipchat.com/#narrow/stream/295306-nearinc-contract-runtime

We need to 
1. get all existing contracts
2. split them into groups by uniqueness of their source code
3. compute how many invocations do we have for each group. How many groups do we have with at least one invocation

(1) should be easily collected by a small modification of `deployed_contracts` table
(2) could be done on python side
Info for (3) is in `daily_receipts_per_contract_count`, we can take number of invocation here

**Comment by Sudiptobhukta** [comment]
Can you explain what is the issue is about?

**Comment by telezhnaya** [comment]
@Sudiptobhukta we had the discussion in zulip, where people asked for the new stats. The issue contains the plan of what should be done

**Comment by Sudiptobhukta** [comment]
> @Sudiptobhukta we had the discussion in zulip, where people asked for the new stats. The issue contains the plan of what should be done

Actually i am not in Zulip would it help if I join it

**Comment by telezhnaya** [comment]
Oh, sorry. 
There was a lengthy discussion. Not sure it is worth following the whole dialog there.
@Sudiptobhukta, are you ready to help with this?

While I was writing the answer, I understood it's better to change the task a little.
I am sorry, it wasn't clear to me how ambiguous it is for the people without the context. Now I see that it's not clear even for me 😄 

We have 3 entities:
1. account_id. It may contain the contract inside. 
2. code_hash: you can treat it as id for each contract. Each contract has the implementation. If the implementation changes, it's totally new contract for us, with a new hash. So, the pair (account_id, code_hash) is not final, and it can be changed at any time.
3. function calls. The simplest way to measure how popular the contract is. But, it is important, we have function calls to account_id, not to code_hash.

Our first request was "let's compute the number of function calls to each code_hash", or, at least "let's collect all code_hashes with at least one incoming function call". For both tasks: it is possible, but it's not a trivial task at all.

I suggest starting from modifying `deployed_contracts` and the dependencies. I prefer to store there all the deployments, not only new unique ones. Sometimes we need that information, and it's better to keep it.
This is a much easier task, but it still does not sound like the "good first issue". 🙁 
But, if you are ready to help, please ping me here. I have other requests from the team. I will collect them, analyze and create other issues!

**Comment by Sudiptobhukta** [comment]
> Oh, sorry. There was a lengthy discussion. Not sure it is worth following the whole dialog there. @Sudiptobhukta, are you ready to help with this?
> 
> While I was writing the answer, I understood it's better to change the task a little. I am sorry, it wasn't clear to me how ambiguous it is for the people without the context. Now I see that it's not clear even for me 😄
> 
> We have 3 entities:
> 
> 1. account_id. It may contain the contract inside.
> 2. code_hash: you can treat it as id for each contract. Each contract has the implementation. If the implementation changes, it's totally new contract for us, with a new hash. So, the pair (account_id, code_hash) is not final, and it can be changed at any time.
> 3. function calls. The simplest way to measure how popular the contract is. But, it is important, we have function calls to account_id, not to code_hash.
> 
> Our first request was "let's compute the number of function calls to each code_hash", or, at least "let's collect all code_hashes with at least one incoming function call". For both tasks: it is possible, but it's not a trivial task at all.
> 
> I suggest starting from modifying `deployed_contracts` and the dependencies. I prefer to store there all the deployments, not only new unique ones. Sometimes we need that information, and it's better to keep it. This is a much easier task, but it still does not sound like the "good first issue". 🙁 But, if you are ready to help, please ping me here. I have other requests from the team. I will collect them, analyze and create other issues!

Yes I am ready to help but as a new, to this analytics, I would need your help in the implementation
